name: 

on:
  push:
    branches:
      - generative-avatars
  pull_request:
    branches:
      - generative-avatars

jobs:
  surge-publish:

    name: Publish on Surge
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3    

      - name: install modules
        run: yarn install

      - name: compile contract
        run: yarn compile

      - name: compile frontend
        run: yarn build

      - name: Deploy to arcadians-animator.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'arcadians-animator.surge.sh'
          project: './packages/react-app/build'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}